apps/order/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url
from . import views

__author__ = 'peter'


urlpatterns = [
    url(r'^add/(?P<sitter_id>[0-9]+)/$', views.add, name='add'),
    url(r'^cancel/(?P<order_id>[0-9]+)/$', views.cancel, name='cancel'),
    url(r'^confirm/(?P<order_id>[0-9]+)/$', views.confirm, name='confirm'),
    url(r'^accept/(?P<order_id>[0-9]+)/$', views.accept, name='accept'),
    url(r'^decline/(?P<order_id>[0-9]+)/$', views.decline, name='decline'),
    url(r'^master_remove_order/(?P<order_id>[0-9]+)/$', views.master_remove_order, name='master_remove_order'),
    url(r'^sitter_remove_order/(?P<order_id>[0-9]+)/$', views.sitter_remove_order, name='sitter_remove_order'),
    url(r'^master_order_list/(?P<order_status>[a-z]+)/$', views.master_order_list, name='master_order_list'),
    url(r'^sitter_order_list/(?P<order_status>[a-z]+)/$', views.sitter_order_list, name='sitter_order_list'),
]

config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from config.settings import local

admin.autodiscover()

urlpatterns = [
    url(r'^petwu/weixin/', include('apps.weixin.urls', namespace="weixin")),
    url(r'^petwu/user/', include('apps.user.urls', namespace="user")),
    url(r'^petwu/sitter/', include('apps.sitter.urls', namespace="sitter")),
    url(r'^petwu/master/', include('apps.master.urls', namespace="master")),
    url(r'^petwu/pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^petwu/order/', include('apps.order.urls', namespace="order")),
    url(r'^petwu/manage/', include('apps.manage.urls', namespace="manage")),
    url(r'^petwu/img/', include('apps.img.urls', namespace="img")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]
urlpatterns += static(local.MEDIA_URL, document_root=local.MEDIA_ROOT)

apps/order/models.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from datetime import date as pydate
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

__author__ = 'peter'


@python_2_unicode_compatible
class Order(models.Model):
    status_choices = (
        ("ordered", "预约寄养"),
        ("accepted", "接受预约"),
        ("confirmed", "确认寄养"),
        ("sitting", "寄养中"),
        ("completed", "寄养完成"),
        ("canceled", "已取消"),
        ("declined", "已拒绝"),
        ("dated", "已过期"),
    )

    # 主人
    master = models.ForeignKey('master.Master')
    # 寄养师
    sitter = models.ForeignKey('sitter.Sitter')
    # 宠物 寄养宠物id字符串 用','间隔
    pets = models.CharField('寄养宠物', max_length=50, default='')
    # 状态
    status = models.CharField("订单状态", choices=status_choices, max_length=20, default="ordered")
    # 创建时间
    create_date = models.DateTimeField("创建时间", auto_now_add=True)
    # 起始时间
    begin_date = models.DateField("起始时间")
    # 结束时间
    end_date = models.DateField("结束时间")
    # 留言
    message = models.TextField("留言", max_length=200, blank=True)
    # 主人删除标志位
    master_removed = models.BooleanField("主人已删除订单", default=False)
    # 寄养师删除标志位
    sitter_removed = models.BooleanField("寄养师已删除订单", default=False)

    # 获得判断过日期的订单状态
    def _get_order_status(self):
        if self.status == 'ordered':
            if pydate.today() >= self.begin_date:
                self.status = 'dated'
                self.save()
        elif self.status == 'accepted':
            if pydate.today() >= self.begin_date:
                self.status = 'dated'
                self.save()
        elif self.status == 'confirmed':
            if self.begin_date <= pydate.today() <= self.end_date:
                self.status = 'sitting'
                self.save()
            elif pydate.today() > self.end_date:
                self.status = 'completed'
                self.save()
        elif self.status == 'sitting':
            if pydate.today() > self.end_date:
                self.status = 'completed'
                self.save()
        return self.status

    # 通过订单状态获得用于显示的订单状态文本
    def _get_order_status_text(self):
        for status in self.status_choices:
            if status[0] == self.order_status:
                return status[1]
        return '未知状态'

    order_status = property(_get_order_status)

    order_status_text = property(_get_order_status_text)

    def __str__(self):
        return self.master.nickname + "-" + self.sitter.nickname

apps/pet/models.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.db import models
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from apps.common import manage_head_portrait

__author__ = 'peter'

pet_type_choices = (
    ("幼犬", "幼 0-7月"),
    ("小型犬", "小 0-7kg"),
    ("中型犬", "中 8-18kg"),
    ("大型犬", "大 19-45kg"),
    ("猫咪", "猫"),
    ("其他", "其他"),
)


class PetTypeInfo(object):
    type_id = 0
    type_name = 'default_name'
    type_desc = 'default_desc'

    def set_info(self, type_id, name, desc):
        self.type_id = type_id
        self.type_name = name
        self.type_desc = desc


pet_type_info_list = []
for i, pet_type in enumerate(pet_type_choices):
    info = PetTypeInfo()
    info.set_info(i, pet_type[0], pet_type[1])
    pet_type_info_list.append(info)


@python_2_unicode_compatible
class Pet(models.Model):
    sex_choices = (
        ("公", "公"),
        ("母", "母"),
    )
    # 主人
    master = models.ForeignKey('user.UserInfo')
    # 昵称
    nickname = models.CharField("昵称", max_length=50)
    # 类型
    type = models.CharField("类型", choices=pet_type_choices, default="幼犬", max_length=20)
    # 品种(拉布拉多,哈士奇)
    breed = models.CharField("品种", max_length=50)
    # 性别
    sex = models.CharField("性别", choices=sex_choices, default="公", max_length=10)
    # 年龄
    year = models.IntegerField("年龄", default=1)
    month = models.IntegerField("月份", default=1)
    # 头像
    head_portrait = models.OneToOneField("img.Img", verbose_name="头像", null=True, blank=True, on_delete=models.SET_NULL)

    def _get_head_portrait_url(self):
        if self.head_portrait:
            head_portrait_url = self.head_portrait.img.url
        elif self.type == "猫咪":
            head_portrait_url = static("images/head_portrait/pet_cat.png")
        elif self.type == "其他":
            head_portrait_url = static("images/head_portrait/pet_other.png")
        else:
            head_portrait_url = static("images/head_portrait/pet_dog.png")
        return head_portrait_url

    # 显示用的头像路径,包含默认值
    head_portrait_url = property(_get_head_portrait_url)

    def __str__(self):
        return self.nickname


# 当Pet被删除时同时删除其对应的头像
@receiver(pre_delete, sender=Pet)
def on_delete(sender, instance, **kwargs):
    manage_head_portrait.on_delete(sender, instance, **kwargs)


# 当Pet被保存时判断头像的变化情况
@receiver(pre_save, sender=Pet)
def on_save(sender, instance, **kwargs):
    manage_head_portrait.on_save(sender, instance, **kwargs)

apps/user/models.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.contrib.auth.models import User

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from apps.master.models import Master

__author__ = 'peter'


@python_2_unicode_compatible
class UserInfo(models.Model):
    sitter_status_choices = (
        ("未认证", "未认证"),
        ("等待认证管理员", "等待认证管理员"),
        ("等待认证店员", "等待认证店员"),
        ("等待认证寄养师", "等待认证寄养师"),
        ("认证管理员成功", "认证管理员成功"),
        ("认证店员成功", "认证店员成功"),
        ("认证寄养师成功", "认证寄养师成功"),
    )
    # 对应认证用的User
    user = models.OneToOneField(User)
    # 绑定的微信openid
    openid = models.CharField(max_length=100, blank=True, null=True)
    # 用户名
    username = models.CharField(max_length=30)
    # 邮箱
    email = models.EmailField(blank=True)
    # 电话
    phone = models.CharField(max_length=20, blank=True)
    # 地理信息
    # longitude = models.FloatField("经度", blank=True)
    # latitude = models.FloatField("纬度", blank=True)
    # 状态
    status = models.CharField(max_length=20, blank=True)
    # 寄养者id one-to-one
    master = models.OneToOneField("master.Master")
    # 寄养师id many-to-one
    sitter = models.ForeignKey("sitter.Sitter", null=True, blank=True, on_delete=models.SET_NULL)
    # 寄养师状态
    sitter_status = models.CharField(choices=sitter_status_choices, max_length=50, blank=True, default="未认证")

    def add_new_setter(self, sitter):
        pass
        self.sitter = sitter
        if sitter.sitter_type == "寄养师":
            self.sitter_status = "等待认证寄养师"
        else:
            self.sitter_status = "等待认证管理员"
        self.save()

    @staticmethod
    def create_new(user, master=None):
        if not master:
            master = Master.objects.create(nickname=user.username)
        return UserInfo.objects.create(user=user, username=user.username, master=master)

    # 创建用户,以及其对应的UserInfo,Master
    @staticmethod
    def create_user(username, password, email=None):
        user = User.objects.create_user(username=username, password=password, email=email)
        return UserInfo.create_new(user)

    def __str__(self):
        return self.username

apps/order/forms.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.forms import ModelForm, RadioSelect, Select, TextInput, Textarea, ModelMultipleChoiceField, BooleanField
from django.utils.translation import ugettext_lazy as _
from apps.pet.models import Pet
from .models import Order

__author__ = 'peter'


class OrderFormBaseMeta(object):
    model = Order
    widgets = {
        'message': Textarea(attrs={'placeholder': '选填,限200个字符以内'}),
    }
    labels = {
    }


class OrderAddForm(ModelForm):
    class Meta(OrderFormBaseMeta):
        fields = (
            'pets',
            'begin_date',
            'end_date',
            'message'
        )

    def save(self, commit=True):
        if self.instance.master_removed is None:
            self.instance.master_removed = False
        if self.instance.sitter_removed is None:
            self.instance.sitter_removed = False
        return super(OrderAddForm, self).save(commit)

apps/order/views.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.db.models import Q

from apps.sitter.models import Sitter
from .forms import OrderAddForm
from .models import Order

__author__ = 'peter'


@login_required
def home(request):
    ctx = {}
    return render(request, 'master/home.html', ctx)


# 用户下订单
# 成功后订单状态为预约寄养
@login_required
def add(request, sitter_id):
    userinfo = request.user.userinfo
    if request.POST:
        form = OrderAddForm(request.POST)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.master = userinfo.master
            new_order.sitter_id = int(sitter_id)
            pets = request.POST.getlist("pets")
            new_order.pets = ",".join(pets)
            new_order.save()
            # 更新主人电话号码
            userinfo.master.phone = request.POST["phone"]
            userinfo.master.save()
            return redirect("master:home")

    ctx = {
        'form': OrderAddForm(),
        'user_info': userinfo,
        'master': userinfo.master,
        'sitter': Sitter.objects.get(pk=int(sitter_id)),
        'redirect_url_after_add_pet': reverse("order:add", kwargs={'sitter_id': sitter_id}),
    }
    ctx.update(csrf(request))
    return render(request, 'order/add.html', ctx)


# 如果订单状态为预约寄养,则寄养师可以接受预约
# 成功后订单状态为接受预约
@login_required
def accept(request, order_id):
    order = Order.objects.get(pk=order_id)
    # 判断是否是本人
    if order.sitter == request.user.userinfo.sitter:
        if order.order_status == "ordered":
            order.status = "accepted"
            order.save()
    order_status = request.GET.get('next', 'all')
    return redirect('order:sitter_order_list', order_status=order_status)


# 如果订单状态为预约寄养,则寄养师可以拒绝预约
# 成功后订单状态为已预约
@login_required
def decline(request, order_id):
    order = Order.objects.get(pk=order_id)
    # 判断是否是本人
    if order.sitter == request.user.userinfo.sitter:
        if order.order_status == "ordered":
            order.status = "declined"
            order.save()
    order_status = request.GET.get('next', 'all')
    return redirect('order:sitter_order_list', order_status=order_status)


# 如果订单状态为接受预约,则主人可以确认寄养
# 成功后订单状态为确认寄养
@login_required
def confirm(request, order_id):
    order = Order.objects.get(pk=order_id)
    # 判断是否是本人
    if order.master == request.user.userinfo.master:
        if order.order_status == "accepted":
            order.status = "confirmed"
            order.save()
    order_status = request.GET.get('next', 'all')
    return redirect('order:master_order_list', order_status=order_status)


# 如果订单状态为预约寄养或接受预约,则主人可以取消预约
# 成功后订单状态为已取消
@login_required
def cancel(request, order_id):
    order = Order.objects.get(pk=order_id)
    # 判断是否是本人
    if order.master == request.user.userinfo.master:
        if order.order_status == "ordered" or order.order_status == "accepted":
            order.status = "canceled"
            order.save()
    order_status = request.GET.get('next', 'all')
    return redirect('order:master_order_list', order_status=order_status)


@login_required
def master_remove_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    # 判断是否是本人
    if order.master == request.user.userinfo.master:
        order.master_removed = True
        order.save()
    order_status = request.GET.get('next', 'all')
    return redirect('order:master_order_list', order_status=order_status)


@login_required
def sitter_remove_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    # 判断是否是本人
    if order.sitter == request.user.userinfo.sitter:
        order.sitter_removed = True
        order.save()
    order_status = request.GET.get('next', 'all')
    return redirect('order:sitter_order_list', order_status=order_status)


@login_required
def master_order_list(request, order_status):
    userinfo = request.user.userinfo
    orders = Order.objects.filter(master=userinfo.master).filter(master_removed=False)
    if order_status != 'all':
        if order_status == 'others':
            orders = orders.filter(Q(status='canceled') | Q(status='declined') | Q(status='dated'))
        else:
            orders = orders.filter(status=order_status)
    ctx = {
        'orders': orders,
        'next': order_status,
    }
    return render(request, 'order/master_order_list.html', ctx)


@login_required
def sitter_order_list(request, order_status):
    userinfo = request.user.userinfo
    orders = Order.objects.filter(sitter=userinfo.sitter).filter(sitter_removed=False)
    if order_status != 'all':
        if order_status == 'others':
            orders = orders.filter(Q(status='canceled') | Q(status='declined') | Q(status='dated'))
        else:
            orders = orders.filter(status=order_status)
    ctx = {
        'orders': orders,
        'next': order_status,
    }
    return render(request, 'order/sitter_order_list.html', ctx)

apps/order/templates/order/add.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}预约寄养师{% endblock %}

{% block head_css %}
    <link rel="stylesheet" href="{% static 'vendor/kalendae-0.5.5/kalendae_petwu.css' %}" type="text/css">
{% endblock %}
{% block head_javascript %}
    <script src="{% static 'vendor/kalendae-0.5.5/kalendae.standalone.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/calender.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.validate.js' %}"></script>
    <script src="{% static 'js/rules.js' %}"></script>
    <script>
        {# 设置汉语 #}
        setKalendaeLocale();

        var cant_date = "{{ sitter.cant_date }}".split(",");

        var kalendaeSettings = {
            months: 1,
            weekStart: 1,
            direction: 'future',
            titleFormat: 'YYYY, MMMM',
            // 设置不能选择的日期项
            blackout: cant_date
        };

        function createRangeKalendae() {
            var settings = kalendaeSettings;
            settings['mode'] = 'range';
            $("#kalendae").kalendae(settings);
        }


        // 读取#sitter_can_pet_list下input里的数据,并生成对应表
        // 对比petlist表，查看宠物类型，状态，做出相应操作


        $(function () {
            createRangeKalendae();
            {# 日期提交按钮 #}
            $("#submit_date").click(function () {
                // 设置提交的日期值
                $("#date_form").find("[name='date_list']").val($("#kalendae").data('kalendae').getSelected());
            });

            {# 截获日期选择事件 #}
            $("#kalendae").data("kalendae").subscribe('change', function (date) {
                var begDate, endDate;
                var selectedDate = this.getSelectedAsText();
                begDate = selectedDate[0];
                if (selectedDate.length == 2) {
                    endDate = selectedDate[1];
                } else {
                    endDate = selectedDate[0];
                }
                // 判断是否能选
                for (var i = 0; i < cant_date.length; i++) {
                    if (Kalendae.moment(cant_date[i]).isBetween(begDate, endDate)) {
                        alert("选择的日期中包含不能选择的日期");
                        this.removeSelected(begDate);
                        this.removeSelected(endDate);
                        return;
                    }
                }
                // 将日期设置到表单hidden项
                $("#begin_date").val(begDate);
                $("#end_date").val(endDate);
            });

        });
    </script>
    <script>
        //手机号，宠物，date,勾选协议表单验证
        var FormValidate = function () {
            $("form").validate({
                ignore: "",
                rules: {
                    begin_date: {
                        required: true
                    },
                    phone: {
                        required: true,
                        isMobile: true
                    },
                    agreement: {
                        required: true
                    },
                    pets: {
                        required: true
                    }
                },
                messages: {
                    begin_date: {
                        required: "请选择寄養日期"
                    },
                    phone: {
                        required: "请输入您的联系手机号"
                    },
                    agreement: {
                        required: "请阅读并同意协议"
                    }, pets: {
                        required: "请至少选择一个宠物"
                    }
                },
                errorPlacement: function (error, element) {
                    if (element.is("[name='pets']")) {               // 宠物选择错误信息
                        error.appendTo($("#pet_selected_error"));
                    } else if (element.is("[name='begin_date']")) {  // 日期选择错误信息
                        error.appendTo($("#date_selected_error"));
                    } else {
                        error.appendTo(element.parent());
                    }
                }
            });
        };
        var petlist = {};   //全局对象

        $(function () {
            //表单验证
            FormValidate();
            // 判断宠物是否选择正确
            $("#sitter_can_pet_list").find("input").each(function () {
                var value = ($(this).val());
                var dataname = ($(this).attr("data-name"));
                petlist[dataname] = value;
            });
            $("#pet_selected").find("[type='checkbox']").change(function () {
                if ($(this).prop('checked')) {
                    if (!($(this).siblings("[name='pet_type']").val() in petlist)) {
                        $(this).attr("checked", false);
                        alert("此寄养师不接受此类宠物");
                    }
                    if ($(this).siblings("[name='pet_ordered']").val() != 0) {
                        $(this).attr("checked", false);
                        alert("此宠物已经有寄养订单了");
                    }
                }
            })
        });

    </script>
{% endblock %}

{% block content %}

    <div class="wrapper">
        <form class="form-horizontal" action="{% url 'order:add' sitter_id=sitter.pk %}" method="post"
              role="form" enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_header '选择日期' %}
            <div id="kalendae"></div>
            <div id="date_selected_error"></div>

            <input id="begin_date" type="hidden" name="begin_date"/>
            <input id="end_date" type="hidden" name="end_date"/>

            {% bootstrap_header '选择宠物' %}
            <div id="sitter_can_pet_list">
                {% for price in sitter.pet_price_list %}
                    {% if price.0 %}
                        <input type="hidden" data-name="{{ price.2.type_name }}" value="{{ price.1 }}">
                    {% endif %}
                {% endfor %}
            </div>
            <div id="pet_selected">
                <div class="form-group form-group-sm">
                    {% for pet in user_info.pet_set.all %}
                        <div class="col-xs-3">
                            <label class="checkbox" for="pet_{{ pet.pk }}">
                                <input type="checkbox" data-toggle="checkbox" value="{{ pet.pk }}" id="pet_{{ pet.pk }}"
                                       name="pets">
                                <img src="{{ pet.head_portrait_url }}">
                                {{ pet.nickname }}
                                <input type="hidden" name="pet_type" value="{{ pet.type }}">
                                <input type="hidden" name="pet_ordered" value="0">
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="pet_selected_error"></div>

            <a style="width: 80%" class="btn btn-success center-block" type="button"
               href="{% url 'pet:add' %}?next={{ redirect_url_after_add_pet }}">添加宠物</a>

            {% bootstrap_header '联系方式' %}
            <div class="form-group form-group-sm">
                <label for="id_phone" class="col-xs-3 control-label">电话号码</label>

                <div class="col-xs-9">
                    <input type="text" class="form-control" id="id_phone" placeholder="请填写手机号码"
                           name="phone" value="{{ master.phone }}"/>
                </div>
            </div>

            {% bootstrap_header '给寄养师留言' %}
            {% bootstrap_textarea form.message %}

            <div class="form-group form-group-sm">
                <div class="col-xs-10 col-xs-offset-1">
                    <label class="checkbox" for="checkbox_agreement">
                        <input type="checkbox" data-toggle="checkbox" name="agreement" id="checkbox_agreement" checked>
                        同意 <a href="#">陪TA屋宠物寄养服务合作协议</a>
                    </label>
                </div>
            </div>

            <div class="form-group form-group-sm">
                <div class="col-xs-10 col-xs-offset-1">
                    <button style="width: 100%;" class="btn btn-primary" type="submit">确认提交</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

apps/order/templates/order/master_order_list.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}主人订单列表{% endblock %}

{% block head_javascript %}
    <script>
        $(function () {
            $(".confirm_order").click(function () {
                if (!confirm("确定要确认寄养吗?")) {
                    return false;
                }
            });
            $(".cancel_order").click(function () {
                if (!confirm("确定要取消寄养吗?")) {
                    return false;
                }
            });
            $(".remove_order").click(function () {
                if (!confirm("确定要删除此订单吗?")) {
                    return false;
                }
            });
        })
    </script>
{% endblock %}

{% block content %}

    <div class="wrapper">
        {% if not orders %}
            <h3>您还没有相关订单</h3>
        {% else %}
            <table class="table">
                <thead>
                <td>订单号</td>
                <td>订单状态</td>
                <td>寄养师</td>
                <td>寄养宠物</td>
                <td>寄养时间</td>
                <td>下单时间</td>
                <td>操作</td>
                </thead>
                {% for order in orders %}
                    <tr>
                        <td><a href="#">{{ order.id }}</a></td>
                        <td>{{ order.order_status_text }}</td>
                        <td><a href="#">{{ order.sitter }}</a></td>
                        <td><a href="#">{{ order.pets }}</a></td>
                        <td>{{ order.begin_date }}-{{ order.end_date }}</td>
                        <td>{{ order.create_date }}</td>
                        <td>
                            {% if order.order_status == 'ordered' or order.order_status == 'accepted' %}
                                <div class="master_order_list_cancel_order">
                                    <a class="btn btn-danger cancel_order" role="button"
                                       href="{% url 'order:cancel' order_id=order.id %}?next={{ next }}">
                                        取消寄养
                                    </a>
                                </div>
                            {% endif %}

                            {% if order.order_status == 'accepted' %}
                                <div class="master_order_list_confirm_order">
                                    <a class="btn btn-danger confirm_order" role="button"
                                       href="{% url 'order:confirm' order_id=order.id %}?next={{ next }}">
                                        确认寄养
                                    </a>
                                </div>
                            {% endif %}

                            {% if order.order_status == 'declined' or order.order_status == 'canceled' or order.order_status == 'dated' or order.order_status == 'completed' %}
                                <div class="master_order_list_remove_order">
                                    <a class="btn btn-danger remove_order" role="button"
                                       href="{% url 'order:master_remove_order' order_id=order.id %}?next={{ next }}">
                                        删除订单
                                    </a>
                                </div>
                            {% endif %}

                            <a href="#">联系寄养师</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>

{% endblock %}

apps/order/templates/order/sitter_order_list.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}寄养师订单列表{% endblock %}

{% block head_javascript %}
    <script>
        $(function () {
            $(".accept_order").click(function () {
                if (!confirm("确定要接受预约吗?")) {
                    return false;
                }
            });
            $(".decline_order").click(function () {
                if (!confirm("确定要拒绝预约吗?")) {
                    return false;
                }
            });
            $(".remove_order").click(function () {
                if (!confirm("确定要删除此订单吗?")) {
                    return false;
                }
            });
        })
    </script>
{% endblock %}

{% block content %}

    <div class="wrapper">
        {# 订单状态 #}
        <div class="order_status">
            <ul class="clearfix">
                <li><a href="{% url 'order:sitter_order_list' order_status='ordered' %}">待接受</a></li>
                <li><a href="{% url 'order:sitter_order_list' order_status='accepted' %}">待确认</a></li>
                <li><a href="{% url 'order:sitter_order_list' order_status='confirmed' %}">待寄养</a></li>
                <li><a href="{% url 'order:sitter_order_list' order_status='sitting' %}">寄养中</a></li>
                <li><a href="{% url 'order:sitter_order_list' order_status='completed' %}">已完成</a></li>
                <li><a href="{% url 'order:sitter_order_list' order_status='others' %}">其他</a></li>
            </ul>
        </div>

        {% if not orders %}
            <h3>您还没有相关订单</h3>
        {% else %}
            <table class="table">
                <thead>
                <td>订单号</td>
                <td>订单状态</td>
                <td>宠物主人</td>
                <td>寄养宠物</td>
                <td>寄养时间</td>
                <td>下单时间</td>
                <td>操作</td>
                </thead>
                {% for order in orders %}
                    <tr>
                        <td><a href="#">{{ order.id }}</a></td>
                        <td>{{ order.order_status_text }}</td>
                        <td><a href="#">{{ order.master }}</a></td>
                        <td><a href="#">{{ order.pets }}</a></td>
                        <td>{{ order.begin_date }}-{{ order.end_date }}</td>
                        <td>{{ order.create_date }}</td>
                        <td>
                            {% if order.order_status == 'ordered' %}
                                <div class="sitter_order_list_accept_order">
                                    <a class="btn btn-danger accept_order" role="button"
                                       href="{% url 'order:accept' order_id=order.id %}?next={{ next }}">
                                        接受预约
                                    </a>
                                </div>

                                <div class="sitter_order_list_decline_order">
                                    <a class="btn btn-danger decline_order" role="button"
                                       href="{% url 'order:decline' order_id=order.id %}?next={{ next }}">
                                        拒绝预约
                                    </a>
                                </div>
                            {% endif %}
                            {% if order.order_status == 'declined' or order.order_status == 'canceled' or order.order_status == 'dated' or order.order_status == 'completed' %}
                                <div class="master_order_list_remove_order">
                                    <a class="btn btn-danger remove_order" role="button"
                                       href="{% url 'order:sitter_remove_order' order_id=order.id %}?next={{ next }}">
                                        删除订单
                                    </a>
                                </div>
                            {% endif %}

                            <a href="#">联系宠物主人</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>

{% endblock %}