apps/pet/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url

from . import views

__author__ = 'peter'


urlpatterns = [
    url(r'^$', views.PetListView.as_view(), name='list'),
    url(r'^add/$', views.add, name='add'),
    url(r'^del/(?P<pk>[0-9]+)/$', views.remove, name='del'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from config.settings import local

admin.autodiscover()

urlpatterns = [
    url(r'^petwu/weixin/', include('apps.weixin.urls', namespace="weixin")),
    url(r'^petwu/user/', include('apps.user.urls', namespace="user")),
    url(r'^petwu/sitter/', include('apps.sitter.urls', namespace="sitter")),
    url(r'^petwu/master/', include('apps.master.urls', namespace="master")),
    url(r'^petwu/pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^petwu/order/', include('apps.order.urls', namespace="order")),
    url(r'^petwu/manage/', include('apps.manage.urls', namespace="manage")),
    url(r'^petwu/img/', include('apps.img.urls', namespace="img")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]
urlpatterns += static(local.MEDIA_URL, document_root=local.MEDIA_ROOT)

apps/pet/models.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.db import models
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from apps.common import manage_head_portrait

__author__ = 'peter'

pet_type_choices = (
    ("幼犬", "幼 0-7月"),
    ("小型犬", "小 0-7kg"),
    ("中型犬", "中 8-18kg"),
    ("大型犬", "大 19-45kg"),
    ("猫咪", "猫"),
    ("其他", "其他"),
)


class PetTypeInfo(object):
    type_id = 0
    type_name = 'default_name'
    type_desc = 'default_desc'

    def set_info(self, type_id, name, desc):
        self.type_id = type_id
        self.type_name = name
        self.type_desc = desc


pet_type_info_list = []
for i, pet_type in enumerate(pet_type_choices):
    info = PetTypeInfo()
    info.set_info(i, pet_type[0], pet_type[1])
    pet_type_info_list.append(info)


@python_2_unicode_compatible
class Pet(models.Model):
    sex_choices = (
        ("公", "公"),
        ("母", "母"),
    )
    # 主人
    master = models.ForeignKey('user.UserInfo')
    # 昵称
    nickname = models.CharField("昵称", max_length=50)
    # 类型
    type = models.CharField("类型", choices=pet_type_choices, default="幼犬", max_length=20)
    # 品种(拉布拉多,哈士奇)
    breed = models.CharField("品种", max_length=50)
    # 性别
    sex = models.CharField("性别", choices=sex_choices, default="公", max_length=10)
    # 年龄
    year = models.IntegerField("年龄", default=1)
    month = models.IntegerField("月份", default=1)
    # 头像
    head_portrait = models.OneToOneField("img.Img", verbose_name="头像", null=True, blank=True, on_delete=models.SET_NULL)

    def _get_head_portrait_url(self):
        if self.head_portrait:
            head_portrait_url = self.head_portrait.img.url
        elif self.type == "猫咪":
            head_portrait_url = static("images/head_portrait/pet_cat.png")
        elif self.type == "其他":
            head_portrait_url = static("images/head_portrait/pet_other.png")
        else:
            head_portrait_url = static("images/head_portrait/pet_dog.png")
        return head_portrait_url

    # 显示用的头像路径,包含默认值
    head_portrait_url = property(_get_head_portrait_url)

    def __str__(self):
        return self.nickname


# 当Pet被删除时同时删除其对应的头像
@receiver(pre_delete, sender=Pet)
def on_delete(sender, instance, **kwargs):
    manage_head_portrait.on_delete(sender, instance, **kwargs)


# 当Pet被保存时判断头像的变化情况
@receiver(pre_save, sender=Pet)
def on_save(sender, instance, **kwargs):
    manage_head_portrait.on_save(sender, instance, **kwargs)

apps/pet/views.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView
from django.contrib.staticfiles.templatetags.staticfiles import static
from .form import PetForm
from .models import Pet

__author__ = 'peter'


# 添加宠物
@login_required
def add(request):
    default_redirect_url = "pet:list"
    if request.POST:
        form = PetForm(request.POST)
        if form.is_valid():
            new_pet = form.save(commit=False)
            new_pet.master = request.user.userinfo
            new_pet.save()
            next_url = request.POST.get("next_url", default_redirect_url)
            if len(next_url) == 0:
                next_url = default_redirect_url
            return redirect(next_url)

    ctx = {
        'form': PetForm(),
        'head_portrait_url': static("images/head_portrait/pet_dog.png"),
        'next_url': request.GET.get("next", default_redirect_url)
    }
    ctx.update(csrf(request))
    return render(request, "pet/add.html", ctx)


# 显示宠物详情并修改
@login_required
def detail(request, pk):
    pet = Pet.objects.get(pk=pk)
    if request.POST:
        form = PetForm(request.POST, instance=pet)
        if form.is_valid():
            new_pet = form.save(commit=False)
            new_pet.master = request.user.userinfo
            new_pet.save()
            return redirect("pet:list")

    ctx = {
        'form': PetForm(instance=pet),
        'pet': pet,
    }
    ctx.update(csrf(request))
    return render(request, "pet/detail.html", ctx)


# 显示宠物列表
class PetListView(ListView):
    model = Pet
    template_name = 'pet/list.html'
    context_object_name = 'my_pet_list'

    def get_queryset(self):
        return Pet.objects.filter(master=self.request.user.userinfo)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PetListView, self).dispatch(*args, **kwargs)


# 删除宠物
@login_required
def remove(request, pk):
    pet = Pet.objects.get(pk=pk)
    # 判断是否是本人
    if pet.master == request.user.userinfo:
        pet.delete()
        return HttpResponse("Success")
    return HttpResponse("None")

apps/pet/templates/pet/add.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}添加宠物{% endblock %}

{% block head_javascript %}
    <script src="{% static 'vendor/localResizeIMG-dist/lrz.bundle.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var PetJSON;                //全局JSON
            var PetBreedSelect = function () {
                var TypeName = $("input[name=type]:checked").attr('value');
                if (TypeName != '猫咪' && TypeName != '其他') {
                    TypeName = '狗';
                }

                var oShi = $("#id_breed");                      //根据物种填充对应品种
                oShi.empty();
                for (var i = 0; i < PetJSON[TypeName].length; i++) {
                    $("<option value='" + PetJSON[TypeName][i].n + "'>" + PetJSON[TypeName][i].n + "</option>").appendTo(oShi)
                }
            };
            var PetType = function () {
                $.getJSON("/static/json/pet_type.json", function (result) {
                    PetJSON = result;
                    return PetBreedSelect();                                    //初始化填充
                });

                $(document).on('change', 'input[name=type]', function () {    //之后点击判断种类填充
                    return PetBreedSelect();
                });
            };
            PetType();
        });
    </script>
{% endblock %}
{% block content %}

    <br><br>

    <div class="wrapper">
        <form class="form-horizontal" action="{% url 'pet:add' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next_url" value="{{ next_url }}">

            {% bootstrap_head_portrait_upload form.head_portrait "pet_head" src=head_portrait_url %}
            {% bootstrap_field form.nickname %}
            {% bootstrap_radio form.type %}
            {% bootstrap_select form.breed %}
            {% bootstrap_radio form.sex %}

            <div class="form-group form-group-sm">
                <label for="id_year" class="col-xs-3 control-label">年龄</label>

                <div class="col-xs-9">
                    <div class="input-group">
                        <input type="number" value="1" title="" placeholder="岁" name="year"
                               id="id_year"
                               class="form-control input-sm">
                        <span class="input-group-addon">岁</span>
                        <input type="number" value="0" title="" placeholder="月" name="month"
                               id="id_month"
                               class="form-control input-sm">
                        <span class="input-group-addon">月</span>
                    </div>
                </div>
            </div>


            <button style="width: 80%;" class="btn btn-primary center-block" type="submit">确认提交</button>

        </form>
    </div>
    <br>
    <br>

{% endblock %}

apps/pet/templates/pet/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}宠物详情{% endblock %}

{% block head_javascript %}
    <script src="{% static 'vendor/localResizeIMG-dist/lrz.bundle.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var PetJSON;                //全局JSON
            var PetBreedSelect = function () {
                var TypeName = $("input[name=type]:checked").attr('value');
                if (TypeName != '猫咪' && TypeName != '其他') {
                    TypeName = '狗';
                }

                var oShi = $("#id_breed");                      //根据物种填充对应品种
                oShi.empty();
                for (var i = 0; i < PetJSON[TypeName].length; i++) {
                    $("<option value='" + PetJSON[TypeName][i].n + "'>" + PetJSON[TypeName][i].n + "</option>").appendTo(oShi)
                }
            };
            var PetType = function () {
                $.getJSON("/static/json/pet_type.json", function (result) {
                    PetJSON = result;
                    return PetBreedSelect();                                    //初始化填充
                });

                $(document).on('change', 'input[name=type]', function () {    //之后点击判断种类填充
                    return PetBreedSelect();
                });
            };
            PetType();
        });
    </script>
{% endblock %}
{% block content %}

    <br><br>

    <div class="wrapper">
        <form class="form-horizontal" action="{% url 'pet:detail' pk=pet.pk %}" method="post">
            {% csrf_token %}

            {% bootstrap_head_portrait_upload form.head_portrait "pet_head" src=pet.head_portrait_url %}
            {% bootstrap_field form.nickname %}
            {% bootstrap_radio form.type %}
            {% bootstrap_select form.breed %}
            {% bootstrap_radio form.sex %}

            <div class="form-group form-group-sm">
                <label for="id_year" class="col-xs-3 control-label">年龄</label>

                <div class="col-xs-9">
                    <div class="input-group">
                        <input type="number" value="{{ form.year.value }}" title="" placeholder="岁" name="year"
                               id="id_year"
                               class="form-control input-sm">
                        <span class="input-group-addon">岁</span>
                        <input type="number" value="{{ form.month.value }}" title="" placeholder="月" name="month"
                               id="id_month"
                               class="form-control input-sm">
                        <span class="input-group-addon">月</span>
                    </div>
                </div>
            </div>


            <button style="width: 80%;" class="btn btn-primary center-block" type="submit">确认提交</button>

        </form>
    </div>
    <br>
    <br>

{% endblock %}

apps/pet/templates/pet/list.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}我的宠物{% endblock %}

{% block head_javascript %}
    {% include 'pet/list_js_base.html' %}
{% endblock %}

{% block content %}

    <div class="wrapper">
        <br><br>
        {% include 'pet/list_list_base.html' %}
    </div>


{% endblock %}

apps/pet/templates/pet/list_js_base.html
<script>
    function delPet(petId) {
        if (confirm("确定要删除此宠物吗?")) {
            var url = "{% url 'pet:del' pk=123456 %}".replace(/123456/, petId);
            $.get(url, function (ret) {
                if (ret == 'Success') {
                    $("#pet_" + petId).remove();
                }
            });
        }
    }
    $(function () {


    })
</script>

apps/pet/templates/pet/list_list_base.html
{% if my_pet_list %}
    <ul id="pet_list_ul" class="clearfix">
        {% for pet in my_pet_list %}
            <li id='pet_{{ pet.pk }}' class='pet_list_li clearfix'>
                <div class="pet_list_del_pet">
                    <button class="btn btn-danger del_pet" type="button" onclick="delPet({{ pet.pk }})">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </div>
                <div onclick="location='{% url 'pet:detail' pk=pet.pk %}'">
                    <div class="pet_list_left">
                        <img src="{{ pet.head_portrait_url }}">
                    </div>
                    <div class="pet_list_right">
                        <span class="pet_list_name">{{ pet.nickname }}</span>
                        <span class="pet_list_info">
                            {{ pet.breed }}&nbsp;{{ pet.year }}岁{{ pet.month }}月&nbsp;{{ pet.type }}
                        </span>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p class="text-center">您还没有相关宠物</p>
    <br><br>
{% endif %}

<a style="width: 80%" class="btn btn-success center-block" type="button" href="{% url 'pet:add' %}?next={{ redirect_url_after_add_pet }}">添加宠物</a>