apps/manage/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url

from . import views

__author__ = 'peter'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^sitter/$', views.sitter, name='sitter'),
    url(r'^command/$', views.command, name='command'),
    url(r'^syncdb/$', views.syncdb, name='syncdb'),
    url(r'^migrate/$', views.migrate, name='migrate'),
]

apps/order/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url
from . import views

__author__ = 'peter'


urlpatterns = [
    url(r'^add/(?P<sitter_id>[0-9]+)/$', views.add, name='add'),
    url(r'^cancel/(?P<order_id>[0-9]+)/$', views.cancel, name='cancel'),
    url(r'^confirm/(?P<order_id>[0-9]+)/$', views.confirm, name='confirm'),
    url(r'^accept/(?P<order_id>[0-9]+)/$', views.accept, name='accept'),
    url(r'^decline/(?P<order_id>[0-9]+)/$', views.decline, name='decline'),
    url(r'^master_remove_order/(?P<order_id>[0-9]+)/$', views.master_remove_order, name='master_remove_order'),
    url(r'^sitter_remove_order/(?P<order_id>[0-9]+)/$', views.sitter_remove_order, name='sitter_remove_order'),
    url(r'^master_order_list/(?P<order_status>[a-z]+)/$', views.master_order_list, name='master_order_list'),
    url(r'^sitter_order_list/(?P<order_status>[a-z]+)/$', views.sitter_order_list, name='sitter_order_list'),
]

apps/sitter/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url

from . import views

__author__ = 'peter'

urlpatterns = [
    url(r'^add/$', views.add, name='add'),

    url(r'^$', views.list_sitters, name='list'),
    url(r'^page/(?P<page>[0-9]+)/$', views.list_sitters_page, name='page'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    url(r'^manage/$', views.manage, name='manage'),
    url(r'^manage/setting/$', views.manage_setting, name='manage_setting'),
    url(r'^manage/setting/info/$', views.manage_setting_info, name='manage_setting_info'),
    url(r'^manage/setting/address/$', views.manage_setting_address, name='manage_setting_address'),
    url(r'^manage/setting/pet/$', views.manage_setting_pet, name='manage_setting_pet'),
    url(r'^manage/setting/my_pet/$', views.manage_setting_my_pet, name='manage_setting_my_pet'),
    url(r'^manage/setting/photo/$', views.manage_setting_photo, name='manage_setting_photo'),
    url(r'^manage/date/$', views.manage_date, name='manage_date'),
    url(r'^manage/order/$', views.manage_order, name='manage_order'),
    url(r'^manage/photo/$', views.manage_photo, name='manage_photo'),
]

config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from config.settings import local

admin.autodiscover()

urlpatterns = [
    url(r'^petwu/weixin/', include('apps.weixin.urls', namespace="weixin")),
    url(r'^petwu/user/', include('apps.user.urls', namespace="user")),
    url(r'^petwu/sitter/', include('apps.sitter.urls', namespace="sitter")),
    url(r'^petwu/master/', include('apps.master.urls', namespace="master")),
    url(r'^petwu/pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^petwu/order/', include('apps.order.urls', namespace="order")),
    url(r'^petwu/manage/', include('apps.manage.urls', namespace="manage")),
    url(r'^petwu/img/', include('apps.img.urls', namespace="img")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]
urlpatterns += static(local.MEDIA_URL, document_root=local.MEDIA_ROOT)

apps/sitter/models.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from datetime import timedelta

from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_delete, pre_save, post_init
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.staticfiles.templatetags.staticfiles import static

from apps.common import manage_head_portrait
from apps.pet.models import PetTypeInfo, pet_type_choices
from apps.sitter.utils import get_distance

__author__ = 'peter'

price_name_list = [
    'pup',
    'small_dog',
    'medium_dog',
    'big_dog',
    'cat',
    'others',
]


class SitterPetPriceInfo(PetTypeInfo):
    price_name = ''
    price_name_desc = ''
    price_enable_name = ''
    price_enable_desc = ''

    def set_price_info(self, info_id, name, desc, price_name):
        super(SitterPetPriceInfo, self).set_info(info_id, name, desc)
        self.price_name = price_name + '_price'
        self.price_name_desc = name + '价格'
        self.price_enable_name = self.price_name + '_enable'
        self.price_enable_desc = '选中' + self.price_name_desc


# 初始化宠物价格信息数组
sitter_pet_price_info_list = []
for i, pet_type in enumerate(pet_type_choices):
    info = SitterPetPriceInfo()
    info.set_price_info(i, pet_type[0], pet_type[1], price_name_list[i])
    sitter_pet_price_info_list.append(info)


@python_2_unicode_compatible
class Sitter(models.Model):
    sitter_type_choices = (
        ("寄养师", "寄养师"),
        ("宠物店", "宠物店"),
        ("寄养场", "寄养场"),
    )
    status_choices = (
        ("等待认证", "等待认证"),
        ("认证成功", "认证成功"),
    )
    sex_choices = (
        ("男", "男"),
        ("女", "女"),
    )
    province_choices = (
        ("北京", "北京"),
        ("天津", "天津"),
        ("河北", "河北"),
        ("山西", "山西"),
        ("内蒙古", "内蒙古"),
        ("辽宁", "辽宁"),
        ("吉林", "吉林"),
        ("黑龙江", "黑龙江"),
        ("上海", "上海"),
        ("江苏", "江苏"),
        ("浙江", "浙江"),
        ("安徽", "安徽"),
        ("福建", "福建"),
        ("江西", "江西"),
        ("山东", "山东"),
        ("河南", "河南"),
        ("湖北", "湖北"),
        ("湖南", "湖南"),
        ("广东", "广东"),
        ("海南", "海南"),
        ("广西", "广西"),
        ("甘肃", "甘肃"),
        ("陕西", "陕西"),
        ("新疆", "新疆"),
        ("青海", "青海"),
        ("宁夏", "宁夏"),
        ("重庆", "重庆"),
        ("四川", "四川"),
        ("贵州", "贵州"),
        ("云南", "云南"),
        ("西藏", "西藏"),
        ("台湾", "台湾"),
        ("澳门", "澳门"),
        ("香港", "香港"),
        ("国外", "国外"),
    )
    pet_price_enable_choices = (
        (0, "否"),
        (1, "是"),
    )
    shop_size_choices = (
        ("小", "小型 1-10只"),
        ("中", "中型 10-50只"),
        ("大", "大型 50只以上"),
    )
    field_size_choices = (
        ("小", "小型 1-50只"),
        ("中", "中型 50-100只"),
        ("大", "大型 100只以上"),
    )
    # 管理员
    manager = models.ForeignKey("user.UserInfo", related_name="manager")
    # 类型(宠物店,专业寄养点,家庭寄养师)
    sitter_type = models.CharField("类型", choices=sitter_type_choices, max_length=20, default='宠物店')
    # 昵称
    nickname = models.CharField("昵称", max_length=50)
    # 联系电话
    phone = models.CharField("联系电话", max_length=20, blank=True)
    # 状态
    status = models.CharField("状态", choices=status_choices, max_length=20, default="等待认证")
    # 个人描述
    desc = models.TextField("个人描述", max_length=500, blank=True)

    # 真实姓名
    realname = models.CharField("真实姓名", max_length=50, blank=True)
    # 性别
    sex = models.CharField("性别", choices=sex_choices, max_length=10, default="男")
    # 邮箱
    email = models.EmailField("邮箱", max_length=50, blank=True)
    # 身份证号
    id_number = models.CharField("身份证号", max_length=30, blank=True)
    # 组织机构代码
    group_number = models.CharField("组织机构代码", max_length=50, blank=True)
    # 职业
    occupation = models.CharField("职业", max_length=20, blank=True)

    # 保存经纬度信息
    longitude = models.FloatField("经度", blank=True)
    latitude = models.FloatField("纬度", blank=True)

    # 省份
    province = models.CharField("省份", choices=province_choices, max_length=50, default="成都")
    # 城市
    city = models.CharField("城市", max_length=50, blank=True)
    # 区/县
    county = models.CharField("区县", max_length=50, blank=True)
    # 街道/小区
    street = models.CharField("街道/小区", max_length=50, blank=True)
    # 楼,单元,门牌
    house_number = models.CharField("楼,单元,门牌", max_length=50, blank=True)
    # 房间面积
    space = models.IntegerField("房间面积", blank=True, default=100)
    # 宠物店规模
    shop_size = models.CharField("宠物店规模", choices=shop_size_choices, max_length=20, default="小")
    # 寄养场规模
    field_size = models.CharField("寄养场规模", choices=field_size_choices, max_length=20, default="小")

    # 饲养经验
    experience = models.IntegerField("饲养经验", default=0)

    # 特色服务
    special_service = models.CharField("特色服务", max_length=100, blank=True)
    # 头像
    head_portrait = models.OneToOneField("img.Img", verbose_name="头像", null=True, blank=True, on_delete=models.SET_NULL)
    # 星级
    star = models.IntegerField("星级", default=0)

    # 推荐人电话
    referee_phone = models.CharField("推荐人电话", max_length=20, blank=True)

    # 不接受寄养日期
    cant_date = models.TextField("不接受寄养日期", max_length=800, blank=True)

    def _get_min_price(self):
        price_list = []
        for price in self.pet_price_list:
            if price[0]:
                price_list.append(price[1])

        if len(price_list) == 0:
            return 0
        return min(price_list)

    # 最低价格
    min_price = property(_get_min_price)

    def _get_head_portrait_url(self):
        if self.head_portrait:
            return self.head_portrait.img.url
        elif self.sex == '男':
            return static("images/head_portrait/male.png")
        else:
            return static("images/head_portrait/female.png")

    # 显示用的头像路径,包含默认值
    head_portrait_url = property(_get_head_portrait_url)

    # 获得单个寄养师
    @staticmethod
    def get(pk):
        return Sitter.objects.get(pk=pk)

    # 获得所有寄养师
    @staticmethod
    def get_all():
        # TODO 添加认证成功限定
        # return Sitter.objects.filter(status="认证成功")
        return Sitter.objects.all()

    # 搜索昵称或地址
    @staticmethod
    def search_nickname_or_address(queryset, search_value):
        if len(search_value) > 0:
            queryset = queryset.filter(
                Q(nickname__contains=search_value) |
                Q(city__contains=search_value) |
                Q(county__contains=search_value) |
                Q(street__contains=search_value) |
                Q(house_number__contains=search_value))
        return queryset

    # 按寄养日期来过滤寄养师
    @staticmethod
    def filter_date(queryset, beg_date, end_date):
        if beg_date and end_date:
            delta = end_date - beg_date
            for i in range(delta.days + 1):
                exclude_date = beg_date + timedelta(days=i)
                queryset = queryset.exclude(cant_date__contains=exclude_date)
        return queryset

    # 按寄养师类型来过滤寄养师
    @staticmethod
    def filter_sitter_type(queryset, sitter_type):
        if sitter_type:
            queryset = queryset.filter(sitter_type=sitter_type)
        return queryset

    # 按宠物类型过滤寄养师
    @staticmethod
    def filter_pet_type(queryset, pet_type):
        if pet_type:
            if pet_type == '幼犬':
                queryset = queryset.filter(pup_price_enable=1)
            elif pet_type == '小型犬':
                queryset = queryset.filter(small_dog_price_enable=1)
            elif pet_type == '中型犬':
                queryset = queryset.filter(medium_dog_price_enable=1)
            elif pet_type == '大型犬':
                queryset = queryset.filter(big_dog_price_enable=1)
            elif pet_type == '猫咪':
                queryset = queryset.filter(cat_price_enable=1)
            elif pet_type == '其他':
                queryset = queryset.filter(others_price_enable=1)
        return queryset

    # 按距离排序
    # TODO 按距离排序,现在用户少,可以用粗暴的排序方式,以后有主机了一定要改为GeoDjango的方式
    @staticmethod
    def sort_by_distance(queryset, longitude, latitude):
        if longitude and latitude:
            # 开始排序
            queryset = sorted(queryset,
                              key=lambda sitter: get_distance(
                                  float(longitude), float(latitude), sitter.longitude, sitter.latitude))
        return queryset

    def __str__(self):
        return self.nickname


# 通过宠物价格信息来添加价格字段和是否选中价格字段
for info in sitter_pet_price_info_list:
    Sitter.add_to_class(info.price_name, models.IntegerField(info.price_name_desc, default=50))
    Sitter.add_to_class(info.price_enable_name,
                        models.IntegerField(info.price_enable_desc, choices=Sitter.pet_price_enable_choices, default=0))


# 当寄养师被查询后设置价格和是否选中数组
@receiver(post_init, sender=Sitter)
def on_init(sender, instance, **kwargs):
    instance.pet_price_list = [
        (instance.pup_price_enable, instance.pup_price, sitter_pet_price_info_list[0]),
        (instance.small_dog_price_enable, instance.small_dog_price, sitter_pet_price_info_list[1]),
        (instance.medium_dog_price_enable, instance.medium_dog_price, sitter_pet_price_info_list[2]),
        (instance.big_dog_price_enable, instance.big_dog_price, sitter_pet_price_info_list[3]),
        (instance.cat_price_enable, instance.cat_price, sitter_pet_price_info_list[4]),
        (instance.others_price_enable, instance.others_price, sitter_pet_price_info_list[5])]


# 当寄养师被删除时同时删除其对应的头像
@receiver(pre_delete, sender=Sitter)
def on_delete(sender, instance, **kwargs):
    manage_head_portrait.on_delete(sender, instance, **kwargs)


# 当寄养师被保存时判断头像的变化情况
@receiver(pre_save, sender=Sitter)
def on_save(sender, instance, **kwargs):
    manage_head_portrait.on_save(sender, instance, **kwargs)


# 寄养师可以设置的特色服务
@python_2_unicode_compatible
class SitterSpecialService(models.Model):
    text = models.CharField("标签文本", max_length=20, unique=True)
    enable = models.BooleanField("有效", default=True)
    img = models.CharField("图标", max_length=20)

apps/sitter/forms.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.forms import Form, ModelForm, RadioSelect, Select, TextInput, Textarea, ChoiceField, DateField
from django.utils.translation import ugettext_lazy as _
from apps.img.models import Img
from apps.pet.models import pet_type_choices
from .models import Sitter

__author__ = 'peter'


class SitterFormBaseMeta:
    model = Sitter
    widgets = {
        'sitter_type': RadioSelect(choices=Sitter.sitter_type_choices),
        'desc': Textarea(attrs={'placeholder': '选填,限500个字符以内'}),
        'city': Select(),
        'referee_phone': TextInput(attrs={'placeholder': '推荐人电话,选填'}),
    }
    labels = {
        'nickname': _('名称'),
        'desc': _('介绍'),
        'realname': _('姓名'),
        'pup_price': _('幼犬'),
        'small_dog_price': _('小型犬'),
        'medium_dog_price': _('中型犬'),
        'big_dog_price': _('大型犬'),
        'cat_price': _('猫咪'),
        'others_price': _('其他'),
        'special_service': _('其他特色'),
    }
    help_texts = {
    }
    error_messages = [
    ]

    def __init__(self):
        pass


class SitterForm(ModelForm):
    class Meta(SitterFormBaseMeta):
        exclude = [
            'manager',
            'status',
            'star',
        ]

    def save(self, commit=True, user_info=None, special_services=None):
        # 保存寄养师信息
        new_sitter = super(SitterForm, self).save(commit=False)
        if user_info:
            new_sitter.manager = user_info
        # 特色服务
        if special_services:
            new_sitter.special_service = ",".join(special_services)
        new_sitter.save(commit)
        return new_sitter


class SitterEnvPhotoForm(ModelForm):
    class Meta:
        model = Img
        exclude = [
            'sitter',
            'type',
        ]


class SitterInfoForm(ModelForm):
    class Meta(SitterFormBaseMeta):
        fields = (
            'head_portrait',
            'desc',
            'occupation',
            'experience',
            'phone',
            'email',
            'space',
            'shop_size',
            'field_size',
        )


class SitterAddressForm(ModelForm):
    class Meta(SitterFormBaseMeta):
        fields = (
            'province',
            'city',
            'county',
            'street',
            'house_number',
        )


class SitterPetForm(ModelForm):
    class Meta(SitterFormBaseMeta):
        fields = (
            'pup_price',
            'pup_price_enable',
            'small_dog_price',
            'small_dog_price_enable',
            'medium_dog_price',
            'medium_dog_price_enable',
            'big_dog_price',
            'big_dog_price_enable',
            'cat_price',
            'cat_price_enable',
            'others_price',
            'others_price_enable',
            'special_service',
        )


class SitterMyPetForm(ModelForm):
    class Meta(SitterFormBaseMeta):
        fields = (
        )


class SitterFilterForm(Form):
    beg_date = DateField(required=False)
    end_date = DateField(required=False)
    pet_type = ChoiceField(label="宠物类型", choices=pet_type_choices, required=False)
    sitter_type = ChoiceField(label="寄养师类型", choices=Sitter.sitter_type_choices, required=False)

apps/sitter/templates/sitter/add.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load model2html %}

{% block head_title %}申请成为寄养师{% endblock %}

{% block head_css %}

{% endblock %}

{% block head_javascript %}
    <script src="{% static 'vendor/localResizeIMG-dist/lrz.bundle.js' %}"></script>
    <script src="{% static 'js/jquery.validate.js' %}"></script>
    <script src="{% static 'js/rules.js' %}"></script>
    <script src="{% static 'js/peter_button.js' %}"></script>
    <script src="{% static 'js/cityselect.js' %}"></script>
    <script>
        // 根据寄养师类型来显示不同的表单项
        var SitterType = function () {
            var TypeId = $("input[name=sitter_type]:checked").attr('id');
            if (TypeId === "id_sitter_type_0") {
                $("#div_group_number,#div_field_size,#div_shop_size").hide();
                $("#div_sex,#div_experience,#div_occupation,#div_space,#div_id_number").show();
                $("label[for='id_nickname']").html('家庭名称');
                $("label[for='id_desc']").html('寄养介绍');
                $("label[for='id_realname']").html('真实姓名');
                $("label[for='id_space']").html('家庭面积');
            } //家庭寄养师
            else if (TypeId === "id_sitter_type_1") {
                $("#div_sex,#div_experience,#div_occupation,#div_space,#div_field_size,#div_id_number").hide();
                $("#div_group_number,#div_shop_size").show();
                $("label[for='id_nickname']").html('宠物店名');
                $("label[for='id_desc']").html('宠物店介绍');
                $("label[for='id_realname']").html('管理员姓名');
            } //宠物店
            else if (TypeId === "id_sitter_type_2") {
                $("#div_sex,#div_occupation,#div_experience,#div_group_number,#div_shop_size").hide();
                $("#div_id_number,#div_space,#div_field_size").show();
                $("label[for='id_nickname']").html('场所名称');
                $("label[for='id_desc']").html('寄养介绍');
                $("label[for='id_realname']").html('管理员姓名');
                $("label[for='id_space']").html('场地面积');
            } //寄养场
        };

        var FormValidate = function () {
            $("form").validate({
                rules: {
                    nickname: {
                        required: true
                    }, email: {
                        required: true,
                        email: true
                    }, desc: {
                        maxlength: 500
                    }, occupation: {
                        required: true
                    }, experience: {
                        required: true,
                        number: true
                    }, id_number: {
                        isIdcardno: true,
                        required: true
                    }, group_number: {
                        isGroupNumber: true,
                        required: true
                    }, realname: {
                        required: true
                    }, phone: {
                        required: true,
                        isMobile: true
                    }, province: {
                        required: true
                    }, city: {
                        required: true
                    }, street: {
                        required: true
                    }, house_number: {
                        required: true
                    }, agreement: {
                        required: true
                    }
                },
                messages: {
                    nickname: {
                        required: "请输入名称"
                    }, email: {
                        required: "请输入您的e-mail地址"
                    }, occupation: {
                        required: "请输入您的职业"
                    }, experience: {
                        required: "请填写您的养宠经验"
                    }, id_number: {
                        required: "请输入您的身份证号码"
                    }, group_number: {
                        required: "请输入组织机构代码或统一社会信用代码"
                    }, realname: {
                        required: "请填写与身份证号对应的姓名"
                    }, phone: {
                        required: "请输入您的手机号码"
                    }, province: {
                        required: "请选择您所在的省份"
                    }, city: {
                        required: "请选择您所在的的城市"
                    }, street: {
                        required: "请填写您所在的街道"
                    }, house_number: {
                        required: "请填写您所在的门牌号"
                    }, agreement: {
                        required: "请阅读并同意协议"
                    }
                },
                errorPlacement: function (error, element) {
                    if (element.is("input[name='agreement']")) {      //协议勾选处
                        error.appendTo(element.parent().parent());
                    } else {
                        error.appendTo(element.parent());
                    }
                }
            });
        };

        $(function () {
            //页面初始化时判断种类
            SitterType();
            //添加表单验证
            FormValidate();

            // 省市县选择
            var province = $('select[name="province"]');
            var city = $('select[name="city"]');
            var county = $('select[name="county"]');
            citySelect("/static/json/city.min.json",
                    province, city, county,
                    $("#city_group"), $("#county_group"),
                    "四川", "成都", "锦江区");

            // 选中checkbox
            $("#checkbox_agreement").prop('checked', true);
        });

        $(document).on('change', 'input[name=sitter_type]', function () {
            //之后点击判断种类
            SitterType();
        });
    </script>
{% endblock %}

{% block content %}

    <div class="wrapper">
        <form role="form" class="form-horizontal" action="{% url 'sitter:add' %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_header '基本信息' %}
            {% bootstrap_radio form.sitter_type %}
            <div id="div_nickname">
                {% bootstrap_field form.nickname %}
            </div>
            <div id="div_desc">
                {% bootstrap_textarea form.desc %}
            </div>
            <div id="div_occupation">
                {% bootstrap_field form.occupation %}
            </div>
            <div id="div_experience">
                {% bootstrap_field form.experience addon_after='年' %}
            </div>

            {% bootstrap_header '隐私信息<small>本项信息保密</small>' %}
            <div id="div_group_number">
                {% bootstrap_field form.group_number %}
            </div>
            <div id="div_realname">
                {% bootstrap_field form.realname %}
            </div>
            <div id="div_id_number">
                {% bootstrap_field form.id_number %}
            </div>
            <div id="div_phone">
                {% bootstrap_field form.phone %}
            </div>

            <div id="div_email">
                {% bootstrap_field form.email %}
            </div>
            <div id="div_sex">
                {% bootstrap_radio form.sex %}
            </div>

            {% bootstrap_header '地址信息' %}

            {# 经度 #}
            <input id="id_longitude" name="longitude" type="hidden" value="">
            {# 纬度 #}
            <input id="id_latitude" name="latitude" type="hidden" value="">

            <div id="province_group">
                {% bootstrap_select form.province %}
            </div>
            <div id="city_group">
                {% bootstrap_select form.city %}
            </div>
            <div id="county_group">
                {% bootstrap_select form.county %}
            </div>
            <div id="div_street">
                {% bootstrap_field form.street %}
            </div>
            <div id="div_house_number">
                {% bootstrap_field form.house_number %}
            </div>
            <div id="div_space">
                {% bootstrap_field form.space addon_after='㎡' %}
            </div>
            <div id="div_shop_size">
                {% bootstrap_radio form.shop_size %}
            </div>
            <div id="div_field_size">
                {% bootstrap_radio form.field_size %}
            </div>

            {% bootstrap_header '可寄养宠物类型/定价' %}
            {% bootstrap_pet_price form.pup_price %}
            {% bootstrap_pet_price form.small_dog_price %}
            {% bootstrap_pet_price form.medium_dog_price %}
            {% bootstrap_pet_price form.big_dog_price %}
            {% bootstrap_pet_price form.cat_price %}
            {% bootstrap_pet_price form.others_price %}

            {% bootstrap_header '特色服务' %}
            {% bootstrap_special_service form.special_service sslist=ss %}

            {% bootstrap_header "上传照片" %}
            {% bootstrap_head_portrait_upload form.head_portrait "sitter_head" src=head_portrait_url %}

            {% bootstrap_header "环境照片" %}
            {% static "images/up_bg.jpeg" as up_bg %}
            {% bootstrap_imgs_upload name="env_photo" icon_src=up_bg img_type='env_photo' %}

            {% bootstrap_field form.referee_phone %}

            <div class="agree_checkbox">
                <span class="selected" onclick="$(this).toggleClass('selected');">
                    <input type="checkbox" style="margin: 0;width: 24px;height: 24px;opacity:0.0" data-toggle="checkbox"
                           name="agreement" id="checkbox_agreement">
                </span>
                <p> 同意 <a href="#">陪TA屋宠物寄养服务合作协议</a></p>
            </div>

            <button style="width: 80%;" class="btn btn-success center-block" type="submit">确认提交</button>
        </form>
        {% bootstrap_imgs_edit_modal name="env_photo" icon_src=up_bg img_type='env_photo' %}
    </div>
    <br>
    <br>
{% endblock %}

{% block footer_javascript %}

    <script>
        var g_latitude = 30.6;
        var g_longitude = 104.1;

        function handle_location(text) {
            $("#id_latitude").val(g_latitude);
            $("#id_longitude").val(g_longitude);
            alert(g_latitude);
            alert(g_longitude);
        }
    </script>
    {% include 'commons/location.html' %}

{% endblock %}

apps/sitter/templates/sitter/list_page.html
{% load staticfiles %}

{% load model2html %}

{% for sitter in sitters %}
    <li class='sitter_list_li clearfix swiper-slide' onclick="location='{% url 'sitter:detail' pk=sitter.pk %}'">
        <div class="sitter_list_left">
            <img src="{{ sitter.head_portrait_url }}">
        </div>
        <div class="sitter_list_right">
            <div class="sitter_list_name">
                <span>{{ sitter.nickname }}</span>
                {# 特色服务徽章 #}
                {% bootstrap_special_service_sign sitter.special_service %}
            </div>
            <div class="sitter_list_desc">
                {{ sitter.desc }}
            </div>
            <div class="sitter_list_other_info">
                <span class="sitter_list_distance">
                    {% get_distance longitude latitude sitter.longitude sitter.latitude %}
                </span>
                <span class="sitter_list_price">
                    {{ sitter.min_price }}￥起
                </span>
                <span class="sitter_list_pet_type">
                    {% for price in sitter.pet_price_list %}
                        {% if price.0 %}
                            <a>{{ price.2.type_name }}</a>
                        {% endif %}
                    {% endfor %}
                </span>
            </div>
        </div>
    </li>
{% endfor %}