apps/pet/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url

from . import views

__author__ = 'peter'


urlpatterns = [
    url(r'^$', views.PetListView.as_view(), name='list'),
    url(r'^add/$', views.add, name='add'),
    url(r'^del/(?P<pk>[0-9]+)/$', views.remove, name='del'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

apps/sitter/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url

from . import views

__author__ = 'peter'

urlpatterns = [
    url(r'^add/$', views.add, name='add'),

    url(r'^$', views.list_sitters, name='list'),
    url(r'^page/(?P<page>[0-9]+)/$', views.list_sitters_page, name='page'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    url(r'^manage/$', views.manage, name='manage'),
    url(r'^manage/setting/$', views.manage_setting, name='manage_setting'),
    url(r'^manage/setting/info/$', views.manage_setting_info, name='manage_setting_info'),
    url(r'^manage/setting/address/$', views.manage_setting_address, name='manage_setting_address'),
    url(r'^manage/setting/pet/$', views.manage_setting_pet, name='manage_setting_pet'),
    url(r'^manage/setting/my_pet/$', views.manage_setting_my_pet, name='manage_setting_my_pet'),
    url(r'^manage/setting/photo/$', views.manage_setting_photo, name='manage_setting_photo'),
    url(r'^manage/date/$', views.manage_date, name='manage_date'),
    url(r'^manage/order/$', views.manage_order, name='manage_order'),
    url(r'^manage/photo/$', views.manage_photo, name='manage_photo'),
]

apps/user/urls.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.conf.urls import url

from . import views

__author__ = 'peter'

urlpatterns = [
    # TODO
    # 在正式发布时去掉
    url(r'^$', views.user_home, name='home'),
    url(r'^reg/$', views.user_reg, name='reg'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from config.settings import local

admin.autodiscover()

urlpatterns = [
    url(r'^petwu/weixin/', include('apps.weixin.urls', namespace="weixin")),
    url(r'^petwu/user/', include('apps.user.urls', namespace="user")),
    url(r'^petwu/sitter/', include('apps.sitter.urls', namespace="sitter")),
    url(r'^petwu/master/', include('apps.master.urls', namespace="master")),
    url(r'^petwu/pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^petwu/order/', include('apps.order.urls', namespace="order")),
    url(r'^petwu/manage/', include('apps.manage.urls', namespace="manage")),
    url(r'^petwu/img/', include('apps.img.urls', namespace="img")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
]
urlpatterns += static(local.MEDIA_URL, document_root=local.MEDIA_ROOT)

apps/user/models.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.contrib.auth.models import User

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from apps.master.models import Master

__author__ = 'peter'


@python_2_unicode_compatible
class UserInfo(models.Model):
    sitter_status_choices = (
        ("未认证", "未认证"),
        ("等待认证管理员", "等待认证管理员"),
        ("等待认证店员", "等待认证店员"),
        ("等待认证寄养师", "等待认证寄养师"),
        ("认证管理员成功", "认证管理员成功"),
        ("认证店员成功", "认证店员成功"),
        ("认证寄养师成功", "认证寄养师成功"),
    )
    # 对应认证用的User
    user = models.OneToOneField(User)
    # 绑定的微信openid
    openid = models.CharField(max_length=100, blank=True, null=True)
    # 用户名
    username = models.CharField(max_length=30)
    # 邮箱
    email = models.EmailField(blank=True)
    # 电话
    phone = models.CharField(max_length=20, blank=True)
    # 地理信息
    # longitude = models.FloatField("经度", blank=True)
    # latitude = models.FloatField("纬度", blank=True)
    # 状态
    status = models.CharField(max_length=20, blank=True)
    # 寄养者id one-to-one
    master = models.OneToOneField("master.Master")
    # 寄养师id many-to-one
    sitter = models.ForeignKey("sitter.Sitter", null=True, blank=True, on_delete=models.SET_NULL)
    # 寄养师状态
    sitter_status = models.CharField(choices=sitter_status_choices, max_length=50, blank=True, default="未认证")

    def add_new_setter(self, sitter):
        pass
        self.sitter = sitter
        if sitter.sitter_type == "寄养师":
            self.sitter_status = "等待认证寄养师"
        else:
            self.sitter_status = "等待认证管理员"
        self.save()

    @staticmethod
    def create_new(user, master=None):
        if not master:
            master = Master.objects.create(nickname=user.username)
        return UserInfo.objects.create(user=user, username=user.username, master=master)

    # 创建用户,以及其对应的UserInfo,Master
    @staticmethod
    def create_user(username, password, email=None):
        user = User.objects.create_user(username=username, password=password, email=email)
        return UserInfo.create_new(user)

    def __str__(self):
        return self.username

apps/user/forms.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import
from django.forms import ModelForm
from .models import UserInfo

__author__ = 'peter'


class UserRegForm(ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            'username',
            'email',
            'phone',
        ]


class UserLoginForm(ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            'username',
        ]

apps/user/views.py
# coding=utf-8
from __future__ import print_function, unicode_literals, absolute_import

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.template.context_processors import csrf

from apps.master.models import Master
from .models import UserInfo

__author__ = 'peter'


@login_required
def user_home(request):
    return render(request, "user/home.html")


def user_reg(request):
    if request.POST:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            UserInfo.create_new(user)
            return redirect("user:login")
        else:
            return redirect("user:reg")
    form = UserCreationForm()
    ctx = {'form': form}
    ctx.update(csrf(request))
    return render(request, 'user/reg.html', ctx)


def user_logout(request):
    logout(request)
    return redirect("user:login")

apps/user/templates/user/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load bootstrap3 %}

{% block head_title %}欢迎回来{% endblock %}

{% block content %}

    {{ user }}

    <br>

    <a href="{% url 'master:home' %}">我是主人</a><br>

    <a href="{% url 'sitter:list' %}">我要寄养</a><br>

    {% if user.userinfo.sitter_status == '认证寄养师成功' %}
        <a href="{% url 'sitter:manage' %}">寄养师后台管理</a><br>
    {% elif user.userinfo.sitter_status == '认证管理员成功' %}
        <a href="{% url 'sitter:manage' %}">管理员后台管理</a><br>
    {% elif user.userinfo.sitter_status == '认证店员成功' %}
        <a href="{% url 'sitter:manage' %}">店员后台管理</a><br>
    {% else %}
        <a href="{% url 'sitter:add' %}">成为寄养师</a><br>
    {% endif %}

    <a href="{% url 'user:logout' %}">注销</a><br>

{% endblock %}

apps/user/templates/user/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load bootstrap3 %}

{% block head_title %}登陆{% endblock %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'user:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        {% bootstrap_form form %}
        {% buttons %}
            <button type=”submit” class=”btn btn-primary” name=”submit”>提交</button>
        {% endbuttons %}
    </form>
{% endblock %}

apps/user/templates/user/reg.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load bootstrap3 %}

{% block head_title %}用户注册{% endblock %}

{% block content %}

    <form role='form' action="{% url 'user:reg' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class=”btn btn-primary” type=”submit” name=”submit”>提交</button>
    </form>

{% endblock %}